export type Locale = 'fr' | 'en';

export const content = {
  fr: {
    nav: {
      home: 'Accueil',
      rsvp: 'RSVP',
      story: 'Notre histoire',
      schedule: 'Programme',
      info: 'Informations',
      gallery: 'Galerie',
    },
    hero: {
      intro: 'Nous allons nous marier',
      title: 'Justine & Fabien',
      date: 'Vendredi, 20 octobre 2023',
      location: 'La Vieille Chapelle, Paris',
      cta: 'RÉPONDRE',
    },
    sections: {
      story: 'Notre histoire',
      schedule: 'Programme',
      info: 'Informations pratiques',
      gallery: 'Galerie',
    },
    countdown: {
      label: 'Jours avant le mariage',
      days: 'Jours',
      hours: 'Heures',
      minutes: 'Minutes',
      seconds: 'Secondes',
      complete: 'Nous sommes mariés !',
    },
    auth: {
      title: 'Espace famille',
      registerTab: 'Créer mon compte',
      loginTab: 'Se connecter',
      householdName: 'Nom du foyer',
      email: 'Email',
      password: 'Mot de passe',
      confirmPassword: 'Confirmer le mot de passe',
      register: 'Créer le compte',
      login: 'Connexion',
      signOut: 'Se déconnecter',
      welcome: 'Bienvenue',
      emptyState: 'Créez votre compte familial pour gérer les réponses et les invités.',
      guestList: 'Invités du foyer',
      addAdult: 'Ajouter un adulte',
      addChild: 'Ajouter un enfant',
      firstName: 'Prénom',
      lastName: 'Nom',
      status: 'Réponse',
      dietary: 'Régime alimentaire',
      allergies: 'Allergies',
      accessibility: 'Besoin d’accessibilité',
      note: 'Note',
      eventCeremony: 'Cérémonie',
      eventDinner: 'Dîner',
      eventBrunch: 'Brunch',
      save: 'Enregistrer les réponses',
      notAnswered: 'Pas encore répondu',
      attending: 'Oui, je viens',
      notAttending: 'Non, je ne viens pas',
    },
  },
  en: {
    nav: {
      home: 'Home',
      rsvp: 'RSVP',
      story: 'Our Story',
      schedule: 'Schedule',
      info: 'Information',
      gallery: 'Gallery',
    },
    hero: {
      intro: 'We are getting married',
      title: 'Justine & Fabien',
      date: 'Friday, 20 October 2023',
      location: 'La Vieille Chapelle, Paris',
      cta: 'RSVP',
    },
    sections: {
      story: 'Our story',
      schedule: 'Schedule',
      info: 'Practical information',
      gallery: 'Gallery',
    },
    countdown: {
      label: 'Days until the wedding',
      days: 'Days',
      hours: 'Hours',
      minutes: 'Minutes',
      seconds: 'Seconds',
      complete: 'We are married!',
    },
    auth: {
      title: 'Household access',
      registerTab: 'Create an account',
      loginTab: 'Log in',
      householdName: 'Household name',
      email: 'Email',
      password: 'Password',
      confirmPassword: 'Confirm password',
      register: 'Create account',
      login: 'Log in',
      signOut: 'Log out',
      welcome: 'Welcome',
      emptyState: 'Create your household account to manage RSVPs and guests.',
      guestList: 'Household guests',
      addAdult: 'Add adult',
      addChild: 'Add child',
      firstName: 'First name',
      lastName: 'Last name',
      status: 'Response',
      dietary: 'Dietary needs',
      allergies: 'Allergies',
      accessibility: 'Accessibility needs',
      note: 'Note',
      eventCeremony: 'Ceremony',
      eventDinner: 'Dinner',
      eventBrunch: 'Brunch',
      save: 'Save responses',
      notAnswered: 'Not answered yet',
      attending: 'Attending',
      notAttending: 'Not attending',
    },
  },
} as const;
